### ISSUE TITLE
"Total Execution Time" not working on Jobs page

### ISSUE THREAD

**Issue by Jacobtims** [mooxphp/jobs#12]
On both the Jobs and Jobs Waiting page the "Total Execution Time" widget is not working.
See screenshot below.
![image](https://github.com/adrolli/filament-job-manager/assets/75219092/7b8a407b-eea6-4f6c-bfb8-a2f566a3139d)

**Comment by adrolli** [comment]
The root of the problem seems to be the 0 seconds job execution time. Why are your jobs that fast? Investigating on rounding to 1s as minimum execution time.

**Comment by Jacobtims** [comment]
The jobs are simple database tasks

**Comment by adrolli** [comment]
Will be fixed in mooxphp/jobs Version 2.0.1
