### ISSUE TITLE
Status column sort issue

### ISSUE THREAD

**Issue by somzoli** [mooxphp/jobs#19]
Hi when i want to sort by status, get an error:

`Column not found: 1054 Unknown column 'status' in 'order clause'`

Query: 

```
SELECT
  *
FROM
  `job_manager`
ORDER BY
  `status` ASC
limit
  10 OFFSET 0
```

Can you manage this? 

Thanks!

Z

**Comment by adrolli** [comment]
Thanks for contributing!

Your issue with sorting jobs requires more steps than obvious in the first sight and introduces a breaking change (db-tables, migration and model). So the only thing I can do now is to remove sortable from the Status column.

We will discuss the needed changes and creation of Moox Jobs V3 in the next couple of days and bring back the sortable feature with some other improvements.
