### ISSUE TITLE
[Bug] Job status stay running

### ISSUE THREAD

**Issue by p-paul** [mooxphp/jobs#25]
Hello,

First off all: Great Job, the pluging resources is very nice and praticle.

I saw a little trouble with the job status when i use the DemoJob from your example. 
The job status never pass to success due to an earler return in you code:
![image](https://github.com/user-attachments/assets/09ea6f11-18d6-4062-9f48-bed34c3a0ed5)

https://github.com/mooxphp/jobs/blob/cd99146344c5308827ab2a8cbdf034a9e34f4150/src/JobManagerProvider.php#L108

I update your code in local and it work correclty after:
```
        if ($failed === false) {
            $attributes += [
                'status' => 'succeeded',
            ];
        } else {
            $attributes += ['status' => 'failed'];
        }
```

Please let me know if this approach is correct.
See ya :)

**Comment by salhdev** [comment]
Hi All,

Here is how I fixed the code :

```
        if ($failed === false) {
            $attributes += [
                'status' => 'succeeded',
            ];
            $monitor->update($attributes);
            return;
        }
```

**Comment by adrolli** [comment]
Hey @p-paul  and @salhdev, 

I was so deep into code that I missed this issue, sorry. Thanks for the issue and the fix! 🎊
I will push out a minor release the next couple of days.

Cheers,
Alf
